### ISSUE TITLE
RemoteExecutionContextDaoTests fails with ClassCastException

### ISSUE THREAD

**Issue by jvalkeal** [jvalkeal/spring-yarn#4]
ExecutionContext needs to know correct types for values in its map. Problem with remote repository over json serialization is that a simple number may be automatically put back as an Integer while context expects it to be i.e. Long.

I believe we need to pass type together with map values so that deserialization can use correct types.

**Comment by jvalkeal** [comment]
Trace for this is:

java.lang.ClassCastException: Value for key=[longKey] is not of type: [class java.lang.Long], it is [(class java.lang.Integer)7]
    at org.springframework.batch.item.ExecutionContext.readAndValidate(ExecutionContext.java:282)
    at org.springframework.batch.item.ExecutionContext.getLong(ExecutionContext.java:184)
    at org.springframework.yarn.batch.repository.RemoteExecutionContextDaoTests.testUpdateContext(RemoteExecutionContextDaoTests.java:80)
